spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none

logging:
  file:
    path: /app/logs

moyeo:
  jwt:
    secret: ${JWT_SECRET}
  oauth:
    apple:
      redirect-uri: ${APPLE_REDIRECT_URI:https://moyeo-web.vercel.app/auth/callback/apple}
